/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * first.java
 *
 * Created on Jun 10, 2012, 1:04:43 AM
 */
package snakegame;

import java.awt.Color;
import java.util.Random;
/**
 *
 * @author Rishabh
 */
public class first extends javax.swing.JFrame {

    /** Creates new form first */
    int die_val=0;
   static int player1_pos=0;
   static int player2_pos=0;
    int x1_pos,y1_pos,x2_pos,y2_pos,x_board,y_board,height,widht,x1_init,y1_init,x2_init,y2_init;
    boolean chck=false;
    Random rand=new Random();
    public first() {
        initComponents();
        int x1,y1;
        x1=board_img.getX();
        y1=board_img.getY();
        height=board_img.getHeight();
        widht=board_img.getWidth();
        System.out.println(x1);
         System.out.println(y1);
          System.out.println(height);
           System.out.println(widht);
            player1_pos=0;
            player2_pos=0;
           /* int pos=5;
             p1_but.setVisible(false);
             
             pos=5;
             x1=(((10-(pos%10))*(widht/10))+50);
             y1=(((9-(pos/10))*(height/10))+50);
             if((pos/10)%2==0)
             {
                x1=((((pos%10)-1)*(widht/10))+50);
             }
                     p2_but.setLocation(x1, y1);
             p2_but.setVisible(true);*/
           p1_but.setVisible(true);
           p2_but.setVisible(true);
           x1_init=p1_but.getX();
           y1_init=p1_but.getY();
           x2_init=p2_but.getX();
           y2_init=p2_but.getY();
           
          // roll_btn.setEnabled(false);
           this.setVisible(true);
            //play();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1_but = new javax.swing.JButton();
        p2_but = new javax.swing.JButton();
        board_img = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        roll_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dieval_txt = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        Label6 = new javax.swing.JLabel();
        Label1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        turn_txt = new javax.swing.JLabel();
        txt2_turn = new javax.swing.JLabel();
        stat_sl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Label_pl1 = new javax.swing.JLabel();
        Label_pl2 = new javax.swing.JLabel();
        score_pl1 = new javax.swing.JLabel();
        score_pl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(null);

        p1_but.setBackground(new java.awt.Color(255, 0, 51));
        p1_but.setForeground(new java.awt.Color(102, 102, 255));
        p1_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snakegame/blue_die.jpg"))); // NOI18N
        p1_but.setText("P1");
        getContentPane().add(p1_but);
        p1_but.setBounds(0, 390, 50, 40);

        p2_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snakegame/red_die.jpg"))); // NOI18N
        p2_but.setText("p2");
        getContentPane().add(p2_but);
        p2_but.setBounds(0, 480, 50, 40);

        board_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snakegame/snakes&ladders.jpg"))); // NOI18N
        board_img.setText("jLabel1");
        getContentPane().add(board_img);
        board_img.setBounds(50, 50, 720, 500);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        roll_btn.setText("Roll Dice");
        roll_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roll_btnMouseClicked(evt);
            }
        });

        jLabel1.setText("You Got !");

        dieval_txt.setText("Dice Value !");

        Label3.setText("3");

        Label2.setText("2");

        Label4.setText("4");

        Label5.setText("5");

        Label6.setText("6");

        Label1.setText("1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roll_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dieval_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roll_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dieval_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(790, 50, 170, 271);

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        turn_txt.setText("Player 1 starts the game.....");

        txt2_turn.setText("Click Roll Dice !");

        stat_sl.setText("No Ladder,No Snake this Time !");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt2_turn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(turn_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(stat_sl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(stat_sl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(turn_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt2_turn)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(790, 340, 200, 100);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), "Scores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Blackadder ITC", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N

        Label_pl1.setText("Player 1");

        Label_pl2.setText("Player 2");

        score_pl1.setText("0");

        score_pl2.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Label_pl2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_pl1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(score_pl1)
                    .addComponent(score_pl2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_pl1)
                    .addComponent(score_pl1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_pl2)
                    .addComponent(score_pl2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(790, 450, 200, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roll_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roll_btnMouseClicked
        // TODO add your handling code here:
        
        int k=rand.nextInt(100);
        k=k%6;
        die_val=k;
        
        int t=0;
        int i;
        for(int j=1;;j++)
        {
            i=j%6;
            t++;
            
            if(i==1)
            {
                Label1.setForeground(Color.BLUE);
                Label2.setForeground(Color.MAGENTA);
                Label3.setForeground(Color.MAGENTA);
                Label4.setForeground(Color.MAGENTA);
                Label5.setForeground(Color.MAGENTA);
                Label6.setForeground(Color.MAGENTA);
                
            }
            else if(i==2)
            {
                Label2.setForeground(Color.BLUE);
                Label1.setForeground(Color.MAGENTA);
                Label3.setForeground(Color.MAGENTA);
                Label4.setForeground(Color.MAGENTA);
                Label5.setForeground(Color.MAGENTA);
                Label6.setForeground(Color.MAGENTA);
                
            }
            else if(i==3)
            {
                Label3.setForeground(Color.BLUE);
                Label2.setForeground(Color.MAGENTA);
                Label1.setForeground(Color.MAGENTA);
                Label4.setForeground(Color.MAGENTA);
                Label5.setForeground(Color.MAGENTA);
                Label6.setForeground(Color.MAGENTA);
                
            }
            else if(i==4)
            {
                Label4.setForeground(Color.BLUE);
                Label1.setForeground(Color.MAGENTA);
                Label2.setForeground(Color.MAGENTA);
                Label3.setForeground(Color.MAGENTA);
                Label5.setForeground(Color.MAGENTA);
                Label6.setForeground(Color.MAGENTA);
                
            }
            else if(i==5)
            {
                Label5.setForeground(Color.BLUE);
                Label1.setForeground(Color.MAGENTA);
                Label2.setForeground(Color.MAGENTA);
                Label3.setForeground(Color.MAGENTA);
                Label4.setForeground(Color.MAGENTA);
                Label6.setForeground(Color.MAGENTA);
                
                
            }
            else if(i==6)
            {
                Label6.setForeground(Color.BLUE);
                Label1.setForeground(Color.MAGENTA);
                Label2.setForeground(Color.MAGENTA);
                Label3.setForeground(Color.MAGENTA);
                Label4.setForeground(Color.MAGENTA);
                Label5.setForeground(Color.MAGENTA);
                
            }
            if(t>70 && j%6==k)
            {
               
                break;
            }
            else
              try{
                  
              } 
               catch(Exception e) {}
        }
        play();
    }//GEN-LAST:event_roll_btnMouseClicked

    public void getPosition(int pos,boolean player)
    {
        if(player==false)  //for player1
        {
             x1_pos=(((10-(pos%10))*(widht/10))+50);
             if(x1_pos<50)
                 x1_pos=77;
            
             y1_pos=(((9-(pos/10))*(height/10))+50);
             if((pos/10)%2==0 && pos/10!=0 && pos%10==0)
                  y1_pos=(((10-(pos/10))*(height/10))+50);
             if(x1_pos>=770)
                 x1_pos=700;
             if((pos/10)%2==0)
             {
                x1_pos=((((pos%10)-1)*(widht/10))+50);
             }
             if((pos%10)==0 && (pos/10)%2==0)
                 x1_pos=77;
            
        }
        else if(player==true) //for player2
        {
            x2_pos=(((10-(pos%10))*(widht/10))+50);
            if(x2_pos<50)
                 x2_pos=77;
             y2_pos=(((9-(pos/10))*(height/10))+50);
              if((pos/10)%2==0 && pos/10!=0 && pos%10==0)
                  y2_pos=(((10-(pos/10))*(height/10))+50);
             if(x2_pos>=770)
                 x2_pos=700;
             if((pos/10)%2==0)
             {
                x2_pos=((((pos%10)-1)*(widht/10))+50);
             }
             if((pos%10)==0 && (pos/10)%2==0)
                 x2_pos=77;
                   
        }
    }
    public void setPlayerpos(int x1,int y1,boolean player)
    {
        if(player==false) //player 1
        {
            p1_but.setLocation(x1,y1);
            p1_but.setVisible(true);
        }
        else if(player==true) //player2
        {
            p2_but.setLocation(x1,y1);
            p2_but.setVisible(true);
        }
    }
   public  void play()
    {
        dieval_txt.setText(Integer.toString(die_val));
     
        
        if(player1_pos<100 || player2_pos<100)
        {
          
            if(chck==false) //player 1 turn
            {
               
                turn_txt.setText("Player 2 Turn Now");
                txt2_turn.setText("Player 2,You Now Click Roll Dice");
                roll_btn.setEnabled(true);
                player1_pos+=die_val;
                checkfunc(player1_pos,false);
                if(player1_pos==player2_pos)
                {
                   player2_pos=0; 
                   setPlayerpos(x2_init,y2_init,true);
                   score_pl2.setText(Integer.toString(player2_pos));
                }
                score_pl1.setText(Integer.toString(player1_pos));
                getPosition(player1_pos,false);
                setPlayerpos(x1_pos,y1_pos,false);
                // roll_btn.setEnabled(false);
                chck=true;
                
            }
            else if(chck==true)
            {
                
                System.out.println(die_val+"die");
                turn_txt.setText("Player 1 Turn Now");
                txt2_turn.setText("Player 1,You Now Click Roll Dice");
                 roll_btn.setEnabled(true);
                player2_pos+=die_val;
                checkfunc(player2_pos,true);
                if(player2_pos==player1_pos)
                {
                   player1_pos=0; 
                   score_pl1.setText(Integer.toString(player1_pos));
                   setPlayerpos(x1_init,y1_init,false);
                }
                score_pl2.setText(Integer.toString(player2_pos));
                getPosition(player2_pos,true);
                setPlayerpos(x2_pos,y2_pos,true);
               //  roll_btn.setEnabled(false);
                chck=false; 
            }
            System.out.println("player: "+x2_pos+"  "+y2_pos+"  "+player2_pos);
        }
        if(player1_pos>=100)
        {
            turn_txt.setText("Player 1 is the Winner !");
            txt2_turn.setText("Congratulations !");
            winner w=new winner(false);
            w.setVisible(true);
            this.setVisible(false);
            roll_btn.setEnabled(false);
        }
        else if(player2_pos>=100)
        {
            turn_txt.setText("Player 2 is the Winner !");
            txt2_turn.setText("Congratulations !");
            winner w=new winner(true);
            w.setVisible(true);
            this.setVisible(false);
            roll_btn.setEnabled(false);
        }
    }
    public void checkfunc(int pos,boolean player)
    {
        //ladders
        if(pos==1)
        { pos=38;stat_sl.setText("Yo! You got a ladder");}
        else if(pos==4)
        {pos=14;stat_sl.setText("Yo! You got a ladder");}
        else if(pos==9)
        {pos=31;stat_sl.setText("Yo! You got a ladder");}
        else if(pos==21)
        {pos=46;stat_sl.setText("Yo! You got a ladder");}
        else if(pos==28)
        {pos=84;stat_sl.setText("Yo! You got a ladder");}
        else if(pos==51)
        {pos=67;stat_sl.setText("Yo! You got a ladder");}
        else if(pos==71)
        { pos=91;stat_sl.setText("Yo! You got a ladder");}
        else if(pos==80)
        {pos=100;stat_sl.setText("Yo! You got a ladder");}
        else if(pos==16)  //Snakes
        {pos=5;stat_sl.setText("ohh! You caught by a snake !");}
        else if(pos==47)
        {pos=26;stat_sl.setText("ohh! You caught by a snake !");}
        else if(pos==49)
        { pos=11;stat_sl.setText("ohh! You caught by a snake !");}
        else if(pos==56)
        {pos=53;stat_sl.setText("ohh! You caught by a snake !");}
        else if(pos==64)
        { pos=60;stat_sl.setText("ohh! You caught by a snake !");}
        else if(pos==87)
        {pos=26;stat_sl.setText("ohh! You caught by a snake !");}
        else if(pos==93)
        {pos=67;stat_sl.setText("ohh! You caught by a snake !");}
        else if(pos==95)
        {pos=86;stat_sl.setText("ohh! You caught by a snake !");}
        else if(pos==98)
        {pos=78;stat_sl.setText("ohh! You caught by a snake !");}
        
        if(player==false)
            player1_pos=pos;
        else if(player==true)
            player2_pos=pos;
    }
    public static void wait2 (){
        long t0,t1;
        t0=System.currentTimeMillis();
        do{
            t1=System.currentTimeMillis();
        }
        while (t1-t0<200);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new first().setVisible(true);
                
            }
        });
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Label_pl1;
    private javax.swing.JLabel Label_pl2;
    public javax.swing.JLabel board_img;
    private javax.swing.JLabel dieval_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JButton p1_but;
    private javax.swing.JButton p2_but;
    private javax.swing.JButton roll_btn;
    private javax.swing.JLabel score_pl1;
    private javax.swing.JLabel score_pl2;
    private javax.swing.JLabel stat_sl;
    private javax.swing.JLabel turn_txt;
    private javax.swing.JLabel txt2_turn;
    // End of variables declaration//GEN-END:variables
}
