/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package wsd;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;

/**
 *
 * @author Rishabh
 */
public class startscreen extends javax.swing.JFrame {

    /**
     * Creates new form startscreen
     */
    public String filename,targetword;
    public startscreen() {
        initComponents();
        this.setLocation(410, 80);
        this.setTitle("Word Sense Disambiguation");
        both.setVisible(false);
      
        tar.setVisible(false);
        both.setText("Choose File or Enter Text");
        tar.setText("Enter Target Word");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        filecontent = new javax.swing.JTextArea();
        both = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        tar = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(520, 650));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel1.setText("WORD SENSE DISAMBIGUATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 20, 270, 30);

        jButton1.setText("Choose File");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 240, 100, 30);

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel3.setText("Enter The Text  (below) :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 70, 300, 17);

        text.setColumns(20);
        text.setRows(5);
        jScrollPane1.setViewportView(text);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 100, 400, 110);

        jLabel2.setText("OR");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 220, 70, 20);

        filecontent.setEditable(false);
        filecontent.setColumns(20);
        filecontent.setRows(5);
        jScrollPane2.setViewportView(filecontent);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 290, 400, 130);
        getContentPane().add(both);
        both.setBounds(110, 430, 270, 30);

        jLabel5.setText("Enter Target Word :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 480, 120, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(200, 480, 140, 30);
        getContentPane().add(tar);
        tar.setBounds(170, 510, 100, 20);

        jButton2.setText("Submit");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(150, 540, 110, 30);

        jLabel4.setText("File Content (If you have choosen the file) :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 270, 360, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
                text.setText(null);
        int returnVal = jFileChooser1.showOpenDialog(this);
      
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = jFileChooser1.getSelectedFile();
        filename=file.getAbsolutePath();
        try {
        
        filecontent.read( new FileReader( file.getAbsolutePath() ), null );
        } catch (IOException ex) {
          System.out.println("problem accessing file"+file.getAbsolutePath());
        }
    } else {
        System.out.println("File access cancelled by user.");
    }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String s1=text.getText();
        String s2=filecontent.getText();
        String s3=jTextField1.getText();
        if(s2.isEmpty() && s3.isEmpty())
        {
            both.setVisible(true);
            tar.setVisible(true);
        }
        else if(s2.isEmpty() && s1.isEmpty())
        {
            both.setVisible(true);
        }
        else if(s3.isEmpty())
        {
            tar.setVisible(true);
        }
        else
        {
            both.setVisible(false);
            tar.setVisible(false);
            if(!s1.isEmpty())
            {
                System.out.println("--------------From text-------------------");
                try{
                    FileWriter fs=new FileWriter("C:\\Users\\Rishabh\\Desktop\\out2.txt");
                    filename="C:\\Users\\Rishabh\\Desktop\\out2.txt";
                    
                    targetword=s3;
                    BufferedWriter out=new BufferedWriter(fs);
                    out.write(s1);
                    out.close();
                }
                catch(Exception e){}
               System.out.println("filename = " + filename+" target "+targetword);
                result ob1=new result(targetword,filename);
                ob1.setVisible(true);
                this.setVisible(false);
            }
            else
            {
                System.out.println("--------------From File-------------------");
                targetword=s3;
              
                System.out.println("filename = " + filename+" target "+targetword);
                result ob1=new result(targetword,filename);
                ob1.setVisible(true);
                 this.setVisible(false);
            }
        }
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(startscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(startscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(startscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(startscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new startscreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel both;
    private javax.swing.JTextArea filecontent;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel tar;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
}
