package hospital2;

import java.text.SimpleDateFormat;

public class admitPatient extends javax.swing.JFrame {
    String ward;
    static int wardno=0,bedno=0;
    //String caseno="seq.NEXTVAL";
    String disease;
    String dat;
    String dat2;
    String time,health,regtemp;
   int f=1;
    int regfee;
    int caseseq;
    int regn;
    String date2;
    /** Creates new form admitPatient */
    public admitPatient(registerPatient h) {
        super("Admit Patient");
        initComponents();
      //  q=h;
        fail.setVisible(false);
        regn=h.regseq;
        java.util.Date pre=new java.util.Date();
       // int year=pre.getYear()+1900;
       // int month=pre.getMonth()+1;
        //int date1=pre.getDate();
        int hours=pre.getHours();
        int mins=pre.getMinutes();
        int sec=pre.getSeconds();
        time=""+hours+":"+mins+":"+sec;
       // dat=new java.sql.Date(date1,month,year);
        //SimpleDateFormat df=new SimpleDateFormat(dat);
        SimpleDateFormat formatter= new SimpleDateFormat("yyyy-MM-dd");
        dat = formatter.format(pre);
        dat2=dat;
        labelPutDate.setText(dat2);
        labelPutTime.setText(time);
        labelWard.setVisible(false);
        labelBed.setVisible(false);
        Database db=new Database();
        db.getConnection();
        try{
         db.r=db.stmt.executeQuery("select seq.NEXTVAL from dual");
        if(db.r.next())
        {
            caseseq=db.r.getInt(1);
        }
        //System.out.println("CASE SEQ"+caseseq);
        jLabel4.setText(Integer.toString(caseseq));
        }
        catch(Exception e){}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogSucesss = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        buttonOk = new javax.swing.JButton();
        labelSucess = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelCase = new javax.swing.JLabel();
        labelCaseNo = new javax.swing.JLabel();
        labelDisease = new javax.swing.JLabel();
        labelAdmitDate = new javax.swing.JLabel();
        labelAdmitTime = new javax.swing.JLabel();
        textDisease = new javax.swing.JTextField();
        labelPutDate = new javax.swing.JLabel();
        labelPutTime = new javax.swing.JLabel();
        buttonClear = new javax.swing.JButton();
        buttonSubmit = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        labelDesiredWard = new javax.swing.JLabel();
        labelWard = new javax.swing.JLabel();
        labelWardNo = new javax.swing.JLabel();
        comboWard = new javax.swing.JComboBox();
        labelBedNo = new javax.swing.JLabel();
        labelBed = new javax.swing.JLabel();
        labelAdvance = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        fail = new javax.swing.JLabel();

        dialogSucesss.setAlwaysOnTop(true);
        dialogSucesss.setBounds(new java.awt.Rectangle(471, 284, 337, 231));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        buttonOk.setText("OK");
        buttonOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonOkMouseClicked(evt);
            }
        });

        labelSucess.setFont(new java.awt.Font("Tahoma", 1, 14));
        labelSucess.setText("Patient Admitted Sucessfully");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(labelSucess, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(labelSucess)
                .addGap(57, 57, 57)
                .addComponent(buttonOk)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogSucesssLayout = new javax.swing.GroupLayout(dialogSucesss.getContentPane());
        dialogSucesss.getContentPane().setLayout(dialogSucesssLayout);
        dialogSucesssLayout.setHorizontalGroup(
            dialogSucesssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogSucesssLayout.setVerticalGroup(
            dialogSucesssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(245, 165, 785, 465));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Admission Details");

        labelCase.setText("Case No.");

        labelCaseNo.setText("    ");

        labelDisease.setText("Disease");

        labelAdmitDate.setText("Date of Admission");

        labelAdmitTime.setText("Time of Admission");

        labelPutDate.setText("jLabel8");

        labelPutTime.setText("jLabel9");

        buttonClear.setText("Clear");
        buttonClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClearMouseClicked(evt);
            }
        });

        buttonSubmit.setText("Submit");
        buttonSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSubmitMouseClicked(evt);
            }
        });
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCancelMouseClicked(evt);
            }
        });
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        labelDesiredWard.setText("Ward Type");

        labelWard.setText("Ward No.");

        comboWard.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "General", "ICU" }));
        comboWard.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboWardItemStateChanged(evt);
            }
        });
        comboWard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboWardActionPerformed(evt);
            }
        });

        labelBed.setText("Bed No.");

        labelAdvance.setText("Registration Fees");

        jLabel2.setText("Present Health Condition");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital2/admit.jpg"))); // NOI18N

        jLabel4.setText("jLabel4");

        fail.setText("jLabel5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelWard)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDisease)
                                    .addComponent(labelDesiredWard)
                                    .addComponent(labelBed)
                                    .addComponent(labelAdmitDate)
                                    .addComponent(labelAdmitTime)
                                    .addComponent(jLabel2)
                                    .addComponent(labelAdvance)
                                    .addComponent(labelCase)
                                    .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(textDisease, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(labelPutDate, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(comboWard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                    .addGap(17, 17, 17)
                                                    .addComponent(labelPutTime))
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(labelBedNo, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelWardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fail)
                                            .addComponent(buttonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(78, 78, 78)
                                                .addComponent(jLabel3)
                                                .addGap(197, 197, 197)
                                                .addComponent(labelCaseNo))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(414, 414, 414))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCase)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDisease)
                    .addComponent(textDisease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDesiredWard)
                    .addComponent(comboWard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelWard)
                    .addComponent(labelWardNo, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCaseNo)
                        .addComponent(labelBed))
                    .addComponent(labelBedNo, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAdmitDate)
                    .addComponent(labelPutDate))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAdmitTime)
                    .addComponent(labelPutTime))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(115, 115, 115))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAdvance)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(fail)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(234, 234, 234))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-816)/2, (screenSize.height-638)/2, 816, 638);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClearMouseClicked
       
        textDisease.setText(null);
        
        jLabel4.setVisible(false);
        comboWard.setSelectedIndex(0);
        labelBedNo.setText(null);
        labelWardNo.setText(null);
        labelWard.setVisible(false);
        labelBed.setVisible(false);
        labelCaseNo.setText(null);
       
        jTextArea1.setText(null);
        //textAdvance.setText(null);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClearMouseClicked

    private void buttonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCancelMouseClicked
        //home h = new home();
        this.setVisible(false);
        home q=new home();
        q.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelMouseClicked

    private void buttonOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOkMouseClicked
//        home h = new home();
        this.setVisible(false);
        dialogSucesss.setVisible(false);
        home q=new home();
        q.setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_buttonOkMouseClicked

    private void buttonSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSubmitMouseClicked
        f=1;
        disease = textDisease.getText();
       //ward=comboWard.
        health=jTextArea1.getText();
        jTextArea1.append(health+ "\n");
        jTextArea1.selectAll();
        regtemp=jTextField1.getText();
        //ward="myward";
        System.out.println("ME"+regtemp+"Me2");
        if(!(regtemp.isEmpty()))
        regfee=Integer.parseInt(regtemp);
        else
            regfee=0;
        System.out.println(ward);
        try {
            if(disease.isEmpty() || health.isEmpty() || ward.equals("Select"))
                f=0;
            if(regtemp.charAt(0)<48 || regtemp.charAt(0)>57)
                f=0;
            if(f==1)
            {
        Database d=new Database();
        d.getConnection();
        System.out.println("Inserting to admit");
       
        d.ps=d.con.prepareStatement("insert into admit values(?,?,?,?,?,?,?,?,?)");
        
      //  d.ps.setString(1,regno);
        d.ps.setInt(1,caseseq);
        d.ps.setString(2,disease);
        System.out.println("Disease  "+disease);
        d.ps.setString(3,ward);
        System.out.println("WARD   "+ward);
        d.ps.setInt(4,wardno);
        System.out.println("WARDNO   "+wardno);
        d.ps.setInt(5,bedno);
        System.out.println("bedno  "+bedno);
        d.ps.setString(6,dat2);
        System.out.println("DATE  "+dat2);
        d.ps.setString(7,time);
        System.out.println("TIME  "+time);
        d.ps.setString(8,health);
        System.out.println("health   "+health);
        d.ps.setInt(9,regfee);
        System.out.println("regfee  "+regfee);
        System.out.println("Test-admit");
        d.ps.executeUpdate();
        d.ps.close();
        System.out.println("Inserted to admit");
        d.ps=d.con.prepareStatement("delete from freebed where ward=? and wardno=? and bedno=?");
        d.ps.setString(1,ward);
        d.ps.setInt(2,wardno);
        d.ps.setInt(3,bedno);
        d.ps.executeUpdate();
        System.out.println(regn);
        System.out.println("Deleted from freebed");
        d.ps.close();
        String n="null";
        d.ps=d.con.prepareStatement("update patinfo set caseno=?,ward=?,wardno=?,bedno=? where regno=?");
        d.ps.setInt(1,caseseq);
        d.ps.setString(2,ward);
        d.ps.setInt(3,wardno);
        d.ps.setInt(4,bedno);
        d.ps.setInt(5,regn);
        d.ps.executeUpdate();
        System.out.println("Inserted to patinfo");
        d.ps.close();
        /*d.ps=d.con.prepareStatement("insert into payment values(?,?,?,?,0,0,0,?,0)");
        //d.ps.setString(1,regno);
        d.ps.setString(2,caseno);
        if(caseno.equals("1")){
            d.ps.setInt(3,50);
        }else{
            d.ps.setInt(3,0);
        }
        d.ps.setInt(4,150);
        d.ps.setInt(5,Integer.parseInt(textAdvance.getText()));
        d.ps.executeUpdate();
        d.ps.close();
        d.closeAll();
     */ //d.ps.close();
        int zero=0;
        d.ps=d.con.prepareStatement("insert into payment (regno,caseno,mcharge,scharge,micharge,paid) values(?,?,?,?,?,?)");
        d.ps.setInt(1,regn);
        d.ps.setInt(2,caseseq);
        d.ps.setInt(3,zero);
        d.ps.setInt(4,zero);
        d.ps.setInt(5,zero);
        d.ps.setInt(6, zero);
        d.ps.executeUpdate();
        d.ps.close();
        System.out.println("printedd");
        d.ps=d.con.prepareStatement("insert into wardcharge (regno,caseno,dat,genwardrate,icuwardrate) values(?,?,?,?,?)");
        d.ps.setInt(1,regn);
        d.ps.setInt(2,caseseq);
        d.ps.setString(3,dat2);
        d.ps.setInt(4,zero);
        d.ps.setInt(5,zero);
        d.ps.executeUpdate();
        d.ps.close();
        dialogSucesss.setVisible(true);
        
            }
            
        }
        catch(Exception e) {}
        if(f==0)
        {
            fail.setText("Incorrect Data Entries.");
            fail.setFont(new java.awt.Font("Sylfaen", 1, 14));
            fail.setForeground(new java.awt.Color(204, 0, 0));
            fail.setVisible(true);
        
        }
    
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSubmitMouseClicked

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void comboWardItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboWardItemStateChanged
        // TODO add your handling code here:
        labelBedNo.setText(null);
        labelWardNo.setText(null);
        labelWard.setVisible(false);
        labelBed.setVisible(false);
       // labelAvailable.setText("");
        wardno=0;
        bedno=0;
        try {
        ward=(String)evt.getItem();
        Database d=new Database();
        d.getConnection();
        d.ps=d.con.prepareStatement("select wardno,bedno from freebed where ward=?");
        d.ps.setString(1, ward);
        d.r=d.ps.executeQuery();
        if (d.r.next()) 
        {
            wardno=d.r.getInt(1);
            bedno=d.r.getInt(2);
        }
       
        labelWard.setVisible(true);
        labelBed.setVisible(true);
        labelWardNo.setText(""+wardno);
        labelBedNo.setText(""+bedno);
        
        d.closeAll();
        } catch(Exception e) {}

    }//GEN-LAST:event_comboWardItemStateChanged

    private void comboWardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboWardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboWardActionPerformed

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSubmitActionPerformed

    //admitPatient(){}
    /**
    * @param args the command line arguments
    *//*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admitPatient().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonOk;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JComboBox comboWard;
    private javax.swing.JDialog dialogSucesss;
    private javax.swing.JLabel fail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelAdmitDate;
    private javax.swing.JLabel labelAdmitTime;
    private javax.swing.JLabel labelAdvance;
    private javax.swing.JLabel labelBed;
    private javax.swing.JLabel labelBedNo;
    private javax.swing.JLabel labelCase;
    private javax.swing.JLabel labelCaseNo;
    private javax.swing.JLabel labelDesiredWard;
    private javax.swing.JLabel labelDisease;
    private javax.swing.JLabel labelPutDate;
    private javax.swing.JLabel labelPutTime;
    private javax.swing.JLabel labelSucess;
    private javax.swing.JLabel labelWard;
    private javax.swing.JLabel labelWardNo;
    private javax.swing.JTextField textDisease;
    // End of variables declaration//GEN-END:variables
}
