package hospital2;

import hospital2.Database;
import hospital2.home;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.sql.Date;

public class patientTransfer extends javax.swing.JFrame {
    home q;
    String newward,preward,dat2;
    String regno,caseno,transdate;
    int days,tamt;
    int wardno,bedno,prewardno,prebedno;
    String date;
    java.sql.Date predate;
    java.util.Date pre;
    int f=1;
    /** Creates new form wardTransfer */
    public patientTransfer(home h) {
        super("Transfer Patient");
        q=h;
        initComponents();
        pre=new java.util.Date();
   
        SimpleDateFormat formatter= new SimpleDateFormat("yyyy-MM-dd");
date = formatter.format(pre);
        dat2=date;
        labelPutDate.setText(dat2);
        labelWard.setVisible(false);
        labelBed.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogSucesss = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        labelSucess = new javax.swing.JLabel();
        buttonOk = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelWard = new javax.swing.JLabel();
        textCase = new javax.swing.JTextField();
        buttonTransfer = new javax.swing.JButton();
        labelWardTransfer = new javax.swing.JLabel();
        buttonClear = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        textReg = new javax.swing.JTextField();
        comboWard = new javax.swing.JComboBox();
        labelBed = new javax.swing.JLabel();
        labelWardNo = new javax.swing.JLabel();
        labelBedNo = new javax.swing.JLabel();
        labelError = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelPutDate = new javax.swing.JLabel();
        fail = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        dialogSucesss.setAlwaysOnTop(true);
        dialogSucesss.setBounds(new java.awt.Rectangle(471, 284, 337, 231));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        labelSucess.setFont(new java.awt.Font("Tahoma", 1, 14));
        labelSucess.setText("Patient Transfered Sucessfully");

        buttonOk.setText("OK");
        buttonOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonOkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(labelSucess, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(labelSucess)
                .addGap(47, 47, 47)
                .addComponent(buttonOk)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout dialogSucesssLayout = new javax.swing.GroupLayout(dialogSucesss.getContentPane());
        dialogSucesss.getContentPane().setLayout(dialogSucesssLayout);
        dialogSucesssLayout.setHorizontalGroup(
            dialogSucesssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogSucesssLayout.setVerticalGroup(
            dialogSucesssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(245, 165, 0, 0));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setText("Registration No.:");

        jLabel2.setText("Case No.:");

        jLabel3.setText("New Ward :");

        labelWard.setText("New Ward No.:");

        buttonTransfer.setText("Transfer");
        buttonTransfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonTransferMouseClicked(evt);
            }
        });
        buttonTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTransferActionPerformed(evt);
            }
        });

        labelWardTransfer.setBackground(new java.awt.Color(153, 24, 240));
        labelWardTransfer.setFont(new java.awt.Font("Times New Roman", 0, 24));
        labelWardTransfer.setText("Transfer Patient");

        buttonClear.setText("Clear");
        buttonClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClearMouseClicked(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCancelMouseClicked(evt);
            }
        });
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        comboWard.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Transfer to", "General", "ICU" }));
        comboWard.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboWardItemStateChanged(evt);
            }
        });

        labelBed.setText("New Bed No.:");

        labelWardNo.setText("              ");

        labelBedNo.setText("            ");

        labelError.setText("         ");

        jLabel4.setText("Date of Transfer");

        labelPutDate.setText("jLabel5");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital2/trnsfr.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(labelBed))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(labelBedNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelWardNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelPutDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboWard, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textCase)
                                    .addComponent(textReg, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelError, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addGap(187, 187, 187))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addComponent(buttonTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(buttonCancel))
                            .addComponent(labelWard, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(labelWardTransfer))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(fail, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(labelWardTransfer)
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(textReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(textCase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelError)
                    .addComponent(comboWard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelPutDate))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWard)
                    .addComponent(labelWardNo))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBed, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBedNo, 0, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fail, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-816)/2, (screenSize.height-652)/2, 816, 652);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCancelMouseClicked
        //home h = new home();
        this.setVisible(false);
        q.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelMouseClicked

    private void buttonClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClearMouseClicked
        textCase.setText(null);
        textReg.setText(null);
        comboWard.setSelectedIndex(0);
        labelWardNo.setText(null);
        labelWard.setVisible(false);
        labelBed.setVisible(false);
        labelWardNo.setText(null);
        labelBedNo.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClearMouseClicked

    private void buttonOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOkMouseClicked
        //home h = new home();
        this.setVisible(false);
        dialogSucesss.setVisible(false);
        q.setVisible(true);
        // TODO add your handling code here:
}//GEN-LAST:event_buttonOkMouseClicked

    private void buttonTransferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTransferMouseClicked
        f=1;
        try {
             if(regno.isEmpty() || caseno.isEmpty() || newward.equals("Tranfer to"))
            f=0;
             if(f==1)
             {
            Database d=new Database();
            d.getConnection();
            d.ps=d.con.prepareStatement("insert into freebed values(?,?,?)");
            d.ps.setString(1,preward);
            d.ps.setInt(2,prewardno);
            d.ps.setInt(3,prebedno);
            d.ps.executeUpdate();
            d.ps.close();
            d.ps=d.con.prepareStatement("update patinfo set ward=?,wardno=?,bedno=? where regno=? and caseno=?");
            d.ps.setString(1,newward);
            d.ps.setInt(2,wardno);
            d.ps.setInt(3,bedno);
            d.ps.setString(4, regno);
            d.ps.setString(5, caseno);
            d.ps.executeUpdate();
            d.ps.close();
            d.ps=d.con.prepareStatement("delete from freebed where ward=? and wardno=? and bedno=?");
            d.ps.setString(1,newward);
            d.ps.setInt(2,wardno);
            d.ps.setInt(3,bedno);
            d.ps.executeUpdate();
            d.ps.close();
            System.out.println("date chck");
            d.ps=d.con.prepareStatement("select dat from wardcharge where caseno=?");
           
            d.ps.setInt(1,Integer.parseInt(caseno));
            d.r=d.ps.executeQuery();
            if(d.r.next())
            {  
            transdate=d.r.getString(1);
            } 
            d.ps.close();
            System.out.println("Old date "+transdate);
            System.out.println("present date "+date);
            d.closeAll();
       DateFormat forma;
       Date dt;
       Date d2;
       dt=java.sql.Date.valueOf(transdate);
       //forma=new SimpleDateFormat("dd-MMM-YYYY");
       //dt=(Date)forma.parse(transdate);
       System.out.println("dt "+dt);
       days=(int) ((pre.getTime()-dt.getTime())/(1000*60*60*24));
       System.out.println(days);
       System.out.println(preward);
       System.out.println(regno);
       Database db=new Database();
       db.getConnection();
       if(preward.equals("General"))
       {
           //amt 500
           
           tamt=500*days;
           System.out.println("InGen");
           db.ps=db.con.prepareStatement("update wardcharge set genwardrate=genwardrate+?,dat=? where regno=?");

           db.ps.setInt(1,tamt);
      
           db.ps.setString(2,dat2);
        
           db.ps.setInt(3,Integer.parseInt(regno));
     
           db.ps.executeUpdate();
          
           System.out.println("executed");
           db.closeAll();
       }
       else if(preward.equals("ICU"))
       {
           //amt 1000
           
           System.out.println("InICU");
           tamt=1000*days;
           db.ps=db.con.prepareStatement("update wardcharge set icuwardrate=icuwardrate+?,dat=? where regno=?");
         
           db.ps.setInt(1,tamt);
         
           db.ps.setString(2,dat2);
         
           db.ps.setInt(3,Integer.parseInt(regno));
         
           db.ps.executeUpdate();
                    System.out.println("executed");
           db.closeAll();
       }
           dialogSucesss.setVisible(true); 
             }
       }
        catch(Exception e) {}
     if(f==0)
     {
         fail.setText("Incorrect Data Entries");
            fail.setFont(new java.awt.Font("Sylfaen", 1, 14));
            fail.setForeground(new java.awt.Color(204, 0, 0));
            fail.setVisible(true);
     }
       
    }//GEN-LAST:event_buttonTransferMouseClicked

    private void buttonTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTransferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTransferActionPerformed

    private void comboWardItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboWardItemStateChanged
        f=1;
        labelWard.setVisible(false);
        labelBed.setVisible(false);
        labelWardNo.setText(null);
        labelBedNo.setText(null);
        labelError.setText(null);
        try {
        regno=textReg.getText();
        caseno=textCase.getText();
        newward=(String)evt.getItem();
        if(regno.isEmpty() || caseno.isEmpty() || newward.equals("Tranfer to"))
            f=0;
        if(f==1)
        {
        Database d=new Database();
        d.getConnection();
        d.ps=d.con.prepareStatement("select ward,wardno,bedno from patinfo where regno=? and caseno=?");
        d.ps.setString(1,regno);
        d.ps.setString(2,caseno);
        d.r=d.ps.executeQuery();
        d.r.next();
        preward=d.r.getString(1);
        prewardno=d.r.getInt(2);
        prebedno=d.r.getInt(3);
        d.ps.close();
        if(preward.equals(newward)) {
            labelError.setText("Already in the same Ward.");
            labelError.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
            labelError.setForeground(new java.awt.Color(204, 0, 0));
        }else{
            wardno=0;
            bedno=0;
            d.ps=d.con.prepareStatement("select wardno,bedno from freebed where ward=?");
            d.ps.setString(1, newward);
            d.r=d.ps.executeQuery();
            if (d.r.next()) {
                wardno=d.r.getInt(1);
                bedno=d.r.getInt(2);
            }
            
                labelWard.setVisible(true);
                labelBed.setVisible(true);
                labelWardNo.setText(""+wardno);
                labelBedNo.setText(""+bedno);
            
        }}
        } catch(Exception e){}
    }//GEN-LAST:event_comboWardItemStateChanged

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelActionPerformed

    /**
    * @param args the command line arguments
    *//*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patientTransfer().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonOk;
    private javax.swing.JButton buttonTransfer;
    private javax.swing.JComboBox comboWard;
    private javax.swing.JDialog dialogSucesss;
    private javax.swing.JLabel fail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelBed;
    private javax.swing.JLabel labelBedNo;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelPutDate;
    private javax.swing.JLabel labelSucess;
    private javax.swing.JLabel labelWard;
    private javax.swing.JLabel labelWardNo;
    private javax.swing.JLabel labelWardTransfer;
    private javax.swing.JTextField textCase;
    private javax.swing.JTextField textReg;
    // End of variables declaration//GEN-END:variables

}
