package hospital2;

import hospital2.Database;
import hospital2.home;

public class payDues extends javax.swing.JFrame {
    String regno,caseno;
    home q;
    dischargePatient z;
    int regn,casen,t1,t2,t3,t4,t5,t6,t7,rem;
    int i=0,tot=0;
    int f=1;
    int amount;
    int rcharge,acharge,scharge,mcharge,micharge,wcharge,pay,due;
    /** Creates new form payDues */
    public payDues(home h) {
        super("Payment Portal");
        initComponents();
        fail.setVisible(false);
        q=h;
    }

    public payDues(dischargePatient d) {
        initComponents();
        z=d;
        i=1;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogSucesss = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        labelSucess = new javax.swing.JLabel();
        buttonOk = new javax.swing.JButton();
        jDialog1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        regf = new javax.swing.JLabel();
        mchrg = new javax.swing.JLabel();
        wchrg = new javax.swing.JLabel();
        schrg = new javax.swing.JLabel();
        michrg = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        amt = new javax.swing.JTextField();
        amtpaid = new javax.swing.JLabel();
        amtp = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        amtd = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelReg = new javax.swing.JLabel();
        labelCase = new javax.swing.JLabel();
        textCase = new javax.swing.JTextField();
        labelPayDue = new javax.swing.JLabel();
        labelPay = new javax.swing.JLabel();
        buttonPay = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        textReg = new javax.swing.JTextField();
        regCharge = new javax.swing.JLabel();
        admCharge = new javax.swing.JLabel();
        wardCharge = new javax.swing.JLabel();
        surCharge = new javax.swing.JLabel();
        medCharge = new javax.swing.JLabel();
        misCharge = new javax.swing.JLabel();
        labelPaidAmt = new javax.swing.JLabel();
        fail = new javax.swing.JLabel();

        dialogSucesss.setAlwaysOnTop(true);
        dialogSucesss.setBounds(new java.awt.Rectangle(471, 284, 337, 231));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        labelSucess.setFont(new java.awt.Font("Tahoma", 1, 14));
        labelSucess.setText("Patient Dues Paid Sucessfully");

        buttonOk.setText("OK");
        buttonOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonOkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(labelSucess, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(labelSucess)
                .addGap(48, 48, 48)
                .addComponent(buttonOk)
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout dialogSucesssLayout = new javax.swing.GroupLayout(dialogSucesss.getContentPane());
        dialogSucesss.getContentPane().setLayout(dialogSucesssLayout);
        dialogSucesssLayout.setHorizontalGroup(
            dialogSucesssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogSucesssLayout.setVerticalGroup(
            dialogSucesssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDialog1.setTitle("Payment Information");
        jDialog1.setBounds(new java.awt.Rectangle(100, 100, 500, 500));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setLayout(null);

        jLabel2.setText("Registration charges :");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 30, 110, 14);

        jLabel3.setText("Medicine Charges :");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 60, 100, 14);

        jLabel4.setText("Ward Charges :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 90, 90, 14);

        jLabel5.setText("Surgery Charges (if any) :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 120, 140, 14);

        jLabel6.setText("Miscellaneous Charges :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 150, 120, 14);

        jLabel7.setText("Total Bill Amount :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 180, 100, 14);

        jButton1.setText("PAY");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(100, 290, 70, 30);

        jButton2.setText("CANCEL");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(250, 290, 80, 30);

        regf.setText("jLabel1");
        jPanel3.add(regf);
        regf.setBounds(210, 30, 170, 14);

        mchrg.setText("jLabel1");
        jPanel3.add(mchrg);
        mchrg.setBounds(210, 60, 170, 14);

        wchrg.setText("jLabel1");
        jPanel3.add(wchrg);
        wchrg.setBounds(210, 90, 170, 14);

        schrg.setText("jLabel1");
        jPanel3.add(schrg);
        schrg.setBounds(210, 120, 170, 14);

        michrg.setText("jLabel1");
        jPanel3.add(michrg);
        michrg.setBounds(210, 150, 180, 14);

        total.setText("jLabel1");
        jPanel3.add(total);
        total.setBounds(210, 180, 190, 14);

        jLabel1.setText("Pay Amount :");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(20, 250, 90, 14);
        jPanel3.add(amt);
        amt.setBounds(210, 250, 110, 20);

        amtpaid.setText("Amount Paid :");
        jPanel3.add(amtpaid);
        amtpaid.setBounds(20, 200, 80, 20);

        amtp.setText("jLabel8");
        jPanel3.add(amtp);
        amtp.setBounds(210, 206, 60, 14);

        jLabel8.setText("Amount Due : ");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 230, 80, 14);

        amtd.setText("jLabel9");
        jPanel3.add(amtd);
        amtd.setBounds(210, 230, 34, 14);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(245, 165, 0, 0));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        labelReg.setText("Registration No.:");

        labelCase.setText("Case No.:");

        textCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCaseActionPerformed(evt);
            }
        });
        textCase.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textCaseFocusLost(evt);
            }
        });

        labelPayDue.setText("           ");

        labelPay.setFont(new java.awt.Font("Times New Roman", 0, 24));
        labelPay.setText("Pay Dues");

        buttonPay.setText("SUBMIT");
        buttonPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPayMouseClicked(evt);
            }
        });

        buttonClear.setText("Clear");
        buttonClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClearMouseClicked(evt);
            }
        });
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCancelMouseClicked(evt);
            }
        });

        textReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRegActionPerformed(evt);
            }
        });

        regCharge.setText("         ");

        admCharge.setText("         ");

        wardCharge.setText("         ");

        surCharge.setText("         ");

        medCharge.setText("         ");

        misCharge.setText("         ");

        labelPaidAmt.setText("          ");

        fail.setText("jLabel8");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonClear)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelCase)
                                .addComponent(labelReg)))
                        .addGap(92, 92, 92)
                        .addComponent(buttonPay)
                        .addGap(98, 98, 98)
                        .addComponent(buttonCancel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(labelPay, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(190, 190, 190)
                            .addComponent(fail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(236, 236, 236)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textReg)
                                .addComponent(textCase, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(149, 149, 149)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(misCharge, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(medCharge, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(surCharge, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(138, 138, 138)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(wardCharge)
                                .addComponent(admCharge)
                                .addComponent(regCharge))))
                    .addGap(322, 322, 322)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelPaidAmt)
                        .addComponent(labelPayDue))
                    .addGap(192, 192, 192)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelPay)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelReg))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCase))
                .addGap(18, 18, 18)
                .addComponent(fail)
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(113, 113, 113)
                    .addComponent(labelPaidAmt)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(regCharge)
                            .addGap(18, 18, 18)
                            .addComponent(admCharge)
                            .addGap(18, 18, 18)
                            .addComponent(wardCharge))
                        .addComponent(labelPayDue))
                    .addGap(18, 18, 18)
                    .addComponent(surCharge)
                    .addGap(18, 18, 18)
                    .addComponent(medCharge)
                    .addGap(18, 18, 18)
                    .addComponent(misCharge)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-516)/2, (screenSize.height-338)/2, 516, 338);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonOkMouseClicked
        // TODO add your handling code here:
        dialogSucesss.setVisible(false);
        home h=new home();
        h.setVisible(true);
}//GEN-LAST:event_buttonOkMouseClicked

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

private void textRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRegActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_textRegActionPerformed

private void buttonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCancelMouseClicked
        //home h = new home();
        this.setVisible(false);
        if(i==0) {
            q.setVisible(true);
        } else {
            //textCase.setText(null);
            //textReg.setText(null);
            z.setEnabled(true);
            z.setVisible(true);
        }
        // TODO add your handling code here:
}//GEN-LAST:event_buttonCancelMouseClicked

private void buttonClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClearMouseClicked
        //textAmountPay.setText(null);
        textCase.setText(null);
        textReg.setText(null);
        regCharge.setText(null);
        admCharge.setText(null);
        wardCharge.setText(null);
        surCharge.setText(null);
        medCharge.setText(null);
        misCharge.setText(null);
        labelPaidAmt.setText(null);
        labelPayDue.setText(null);
        // TODO add your handling code here:
}//GEN-LAST:event_buttonClearMouseClicked

private void buttonPayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPayMouseClicked
        regn=Integer.parseInt(textReg.getText());
        casen=Integer.parseInt(textCase.getText());
        
       if(textReg.getText().isEmpty() || textCase.getText().isEmpty())
           f=0;
   
        try{
            if(f==1)
            {
             this.setVisible(false);
        jDialog1.setVisible(true);
        wchrg.setText("0");
            
            Database db=new Database();
        db.getConnection();
        db.ps=db.con.prepareStatement("select regfee from admit where caseno=?");
        db.ps.setInt(1,casen);
       db.r= db.ps.executeQuery();
        if(db.r.next())
        {
            t1=db.r.getInt(1);
        }
        tot+=t1;
        regf.setText(Integer.toString(t1));
        db.ps.close();
        db.ps=db.con.prepareStatement("select mcharge,scharge,micharge,paid from payment where regno=?");
        db.ps.setInt(1,regn);
        db.r=db.ps.executeQuery();
        if(db.r.next())
        {
            t1=db.r.getInt(1);
            t2=db.r.getInt(2);
            t3=db.r.getInt(3);
            t7=db.r.getByte(4);
            tot+=t1+t2+t3;
        }
        mchrg.setText(Integer.toString(t1));
        schrg.setText(Integer.toString(t2));
        michrg.setText(Integer.toString(t3));
        amtp.setText(Integer.toString(t7));
        rem=tot-t7;
        amtd.setText(Integer.toString(rem));
        //total.setText(Integer.toString(tot));
        db.ps.close();
       db.ps=db.con.prepareStatement("select genwardrate,icuwardrate from wardcharge where regno=?");
       db.ps.setInt(1,regn);
       db.r=db.ps.executeQuery();
       if(db.r.next())
       {
           t4=db.r.getInt(1);
           t5=db.r.getInt(2);
           tot+=t4+t5;
        }
       t6=t4+t5;
       wchrg.setText(Integer.toString(t6));
       total.setText(Integer.toString(tot));
       db.ps.close();
            }
        }
        
        catch(Exception e){}
        if(f==0)
        {
            fail.setText("Incorrect Data Entries");
            fail.setFont(new java.awt.Font("Sylfaen", 1, 14));
            fail.setForeground(new java.awt.Color(204, 0, 0));
            fail.setVisible(true);
        }
}//GEN-LAST:event_buttonPayMouseClicked

private void textCaseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textCaseFocusLost
        // TODO add your handling code here:
        
}//GEN-LAST:event_textCaseFocusLost

private void textCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCaseActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_textCaseActionPerformed

private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_buttonClearActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        amount=Integer.parseInt(amt.getText());
        System.out.println(regn+ " "+amount);
        try{
            Database db=new Database();
            db.getConnection();
            db.ps=db.con.prepareStatement("update payment set paid=paid+? where regno=?");
            db.ps.setInt(1,amount);
            db.ps.setInt(2,regn);
            db.ps.executeUpdate();
            db.ps.close();
        
        }
        catch(Exception e) {}
        jDialog1.setVisible(false);
        dialogSucesss.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        home h=new home();
        jDialog1.setVisible(false);
        h.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    /**
    * @param args the command line arguments
    *//*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payDues().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admCharge;
    private javax.swing.JTextField amt;
    private javax.swing.JLabel amtd;
    private javax.swing.JLabel amtp;
    private javax.swing.JLabel amtpaid;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonOk;
    private javax.swing.JButton buttonPay;
    private javax.swing.JDialog dialogSucesss;
    private javax.swing.JLabel fail;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelCase;
    private javax.swing.JLabel labelPaidAmt;
    private javax.swing.JLabel labelPay;
    private javax.swing.JLabel labelPayDue;
    private javax.swing.JLabel labelReg;
    private javax.swing.JLabel labelSucess;
    private javax.swing.JLabel mchrg;
    private javax.swing.JLabel medCharge;
    private javax.swing.JLabel michrg;
    private javax.swing.JLabel misCharge;
    private javax.swing.JLabel regCharge;
    private javax.swing.JLabel regf;
    private javax.swing.JLabel schrg;
    private javax.swing.JLabel surCharge;
    private javax.swing.JTextField textCase;
    private javax.swing.JTextField textReg;
    private javax.swing.JLabel total;
    private javax.swing.JLabel wardCharge;
    private javax.swing.JLabel wchrg;
    // End of variables declaration//GEN-END:variables

}
